# NOTE: Generated By HttpRunner v3.1.4
# FROM: testcases\GameList\game_info.json

import pytest
from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase
from httprunner import Parameters

class TestCaseGloud(HttpRunner):
    @pytest.mark.parametrize(
        "param",
        Parameters(
            {
                "username": "${parameterize(testcases/username.csv)}"
            }
        )
    )
    def test_start(self, param):
        super().test_start(param)
    config = Config("thumb_up_video")
    teststeps = [
        Step(
            RunRequest("thumb_up_video")
            .with_variables(
                **{
                    "token":"${return_token($username)}"
                }
                )
            .get("${ENV(url)}")
            .with_params(
                **{
                    "deviceid": "${ENV(deviceid)}",
                    "ver": "${ENV(ver)}",
                    "pid": "${ENV(pid)}",
                    "logintoken": "$token",        
                    "account_id": "$username",
                    "mode": "${ENV(mode)}",
                    "language": "${ENV(language)}",
                    "lz": "${ENV(lz)}",
                    "hwdeviceid": "${ENV(hwdeviceid)}",
                    "TimeZoneName": "${ENV(TimeZoneName)}",
                    "TimeZoneId": "${ENV(TimeZoneId)}",
                    "version": "${ENV(version)}",
                    "m": "video",
                    "a": "thumb_up_video",
                    "Sint": "27",
                    "video_id": "759805",
                    "type": "short"
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.ret", "${judgment_ret($response)}")
            .assert_not_equal("body.video_list.id","")
        ),
    ]


if __name__ == "__main__":
    TestCaseGameInfo().test_start()
