# NOTE: Generated By HttpRunner v3.1.4
# FROM: testcases\GameList\game_info.json


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseGameInfo(HttpRunner):

    config = Config("game_info")

    teststeps = [
        Step(
            RunRequest("game_info")
            .get("${ENV(url)}")
            .with_params(
                **{
                    "deviceid": "${ENV(deviceid)}",
                    "ver": "${ENV(ver)}",
                    "pid": "${ENV(pid)}",
                    "logintoken": "${ENV(logintoken)}",
                    "account_id": "${ENV(username)}",
                    "mode": "${ENV(mode)}",
                    "language": "${ENV(language)}",
                    "lz": "${ENV(lz)}",
                    "hwdeviceid": "${ENV(hwdeviceid)}",
                    "TimeZoneName": "${ENV(TimeZoneName)}",
                    "TimeZoneId": "${ENV(TimeZoneId)}",
                    "version": "${ENV(version)}",
                    "m": "GameList",
                    "a": "game_info",
                    "gameid": "10841",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.ret", 0)
        ),
    ]


if __name__ == "__main__":
    TestCaseGameInfo().test_start()
