# NOTE: Generated By HttpRunner v3.1.4
# FROM: testcases\GameList\game_info.json

import pytest
from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase
from httprunner import Parameters

class TestCaseGloud(HttpRunner):
    @pytest.mark.parametrize(
        "param",
        Parameters(
            {
                "username": "${parameterize(testcases/username.csv)}"
            }
        )
    )
    def test_start(self, param):
        super().test_start(param)
    config = Config("game_info")
    teststeps = [
        Step(
            RunRequest("game_info")
            .with_variables(
                **{
                    "token":"${return_token($username)}"
                }
                )
            .get("${ENV(url)}")
            .with_params(
                **{
                    "deviceid": "${ENV(deviceid)}",
                    "ver": "${ENV(ver)}",
                    "pid": "${ENV(pid)}",
                    "logintoken": "$token",        
                    "account_id": "$username",
                    "mode": "${ENV(mode)}",
                    "language": "${ENV(language)}",
                    "lz": "${ENV(lz)}",
                    "hwdeviceid": "${ENV(hwdeviceid)}",
                    "TimeZoneName": "${ENV(TimeZoneName)}",
                    "TimeZoneId": "${ENV(TimeZoneId)}",
                    "version": "${ENV(version)}",
                    "m": "GameList",
                    "a": "game_info",
                    "gameid": "10841",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.ret", 0)
        ),
    ]


if __name__ == "__main__":
    TestCaseGameInfo().test_start()
